name: Cable.cr NATSBackend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  specs:
    env:
      CABLE_BACKEND_URL: nats://
    strategy:
      fail-fast: false
      matrix:
        shard_file:
          - shard.yml
        crystal_version:
          - 1.10.0
          - latest
        experimental:
          - false
        include:
          - crystal_version: nightly
            experimental: true
    runs-on: ubuntu-latest
    container: crystallang/crystal:${{ matrix.crystal_version }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Crystal
        uses: actions/cache@v4
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-crystal
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
      - name: Run tests
        run: crystal spec
